import "src/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "src/components/header";
import Main from "src/components/main";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
    const light_logo_url = "/assets/images/logo_light.png";
    const dark_logo_url = "/assets/images/logo_dark.png";

    return (
        <html lang="en">
            <head>
                <title>Home</title>
                <link rel="icon" type="image/x-icon" href={dark_logo_url} />
            </head>
            <body
                className={inter.className + "flex flex-1 grow h-full flex-col"}
            >
                <Header />
                <Main children={children} />
            </body>
        </html>
    );
}
