import "src/app/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Main from "src/components/main";
import NextNProgressClient from "src/components/nextProgess";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AppLayout({ children }: { children: React.ReactNode }) {
    const light_logo_url = "/assets/images/logo_light.png";
    const dark_logo_url = "/assets/images/logo_dark.png";

    return (
        <html lang="en">
            <head>
                <title>Home</title>
                <link rel="icon" type="image/png" href={light_logo_url} />
            </head>
            <body className={inter.className}>
                <NextNProgressClient>
                    <Main children={children} />
                </NextNProgressClient>
            </body>
        </html>
    );
}
