import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "src/components/layout/providers";
import AuthProvider from "src/context/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <Providers>
//         <body className={inter.className}>
//           <AuthProvider>{children}</AuthProvider>
//         </body>
//       </Providers>
//     </html>
//   );
// }
